### ISSUE TITLE
How does the Crusader's Hammer Throw/Paladin's Lightning Wave work?

### ISSUE THREAD

**Issue by Dudejo** [cabbruzzese/gameoftomes#1]
When I use Mouse 2 with either weapon, I only get the regular attack.

Do I have to unlock them somehow?

**Comment by cabbruzzese** [comment]
Yes. One of the design philosophies was to make some elements of the game discoverable. Throwing hammers and shooting the Paladin's lightning are unlocked by gaining at least 14 intelligence.

The crusader can start with 13 Int and should gain the ability at level 2 or 3.

The paladin can start with 10 Int and tends to gain the ability at level 4 or 5.

An aspect I enjoy when playing around with the mod is to reroll stats for the crusader (start a new single player game) until getting a 13 int.

**Comment by cabbruzzese** [comment]
Added to Wiki, and used preview marks as "spoiler" tags. That should be more fun for players who want to discover.
